# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/john/personal_projects/Car_Dashboard/yocto/poky/meta \
  /home/john/personal_projects/Car_Dashboard/yocto/poky/meta-poky \
  /home/john/personal_projects/Car_Dashboard/yocto/poky/meta-yocto-bsp \
  "
